modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="funaethermod"
version="0.0.2-beta"
displayName="Fun Aether Mod"
authors="BLLEEACH"

description='''
d2UgYXJlIHN0aWxsIGhlcmU=
'''

[[dependencies.funaethermod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.funaethermod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"